In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('stock_infosys.csv')
df.head()

           Date    Close     Open     High      Low  Vol-Million  Change %
0  Jun 18, 2018  1269.20  1281.80  1291.00  1264.05         2.86     -0.01
1  Jun 15, 2018  1281.25  1237.00  1291.50  1235.00         9.98      0.03
2  Jun 14, 2018  1239.70  1253.00  1253.00  1234.10         3.80     -0.02
3  Jun 13, 2018  1264.80  1256.86  1273.93  1256.86         2.88      0.01
4  Jun 12, 2018  1248.63  1255.82  1261.28  1240.64         3.92      0.00

In [3]:
df.shape

(249, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         249 non-null    object
 1   Close        249 non-null    float64
 2   Open         249 non-null    float64
 3   High         249 non-null    float64
 4   Low          249 non-null    float64
 5   Vol-Million  249 non-null    float64
 6   Change %     249 non-null    float64
dtypes: float64(6), object(1)
memory usage: 13.7+ KB

In [5]:
# Formatting the date column
df['Date'] = pd.to_datetime(df['Date'])
df.head()

        Date    Close     Open     High      Low  Vol-Million  Change %
0 2018-06-18  1269.20  1281.80  1291.00  1264.05         2.86     -0.01
1 2018-06-15  1281.25  1237.00  1291.50  1235.00         9.98      0.03
2 2018-06-14  1239.70  1253.00  1253.00  1234.10         3.80     -0.02
3 2018-06-13  1264.80  1256.86  1273.93  1256.86         2.88      0.01
4 2018-06-12  1248.63  1255.82  1261.28  1240.64         3.92      0.00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         249 non-null    datetime64[ns]
 1   Close        249 non-null    float64
 2   Open         249 non-null    float64
 3   High         249 non-null    float64
 4   Low          249 non-null    float64
 5   Vol-Million  249 non-null    float64
 6   Change %     249 non-null    float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 13.7 KB

In [ ]:
df.head() # Same range data values so no need of feture scalling

        Date    Close     Open     High      Low  Vol-Million  Change %
0 2018-06-18  1269.20  1281.80  1291.00  1264.05         2.86     -0.01
1 2018-06-15  1281.25  1237.00  1291.50  1235.00         9.98      0.03
2 2018-06-14  1239.70  1253.00  1253.00  1234.10         3.80     -0.02
3 2018-06-13  1264.80  1256.86  1273.93  1256.86         2.88      0.01
4 2018-06-12  1248.63  1255.82  1261.28  1240.64         3.92      0.00

In [8]:
df['Date'] = df['Date'].dt.strftime('%Y%j')
df.head()

      Date    Close     Open     High      Low  Vol-Million  Change %
0  2018169  1269.20  1281.80  1291.00  1264.05         2.86     -0.01
1  2018166  1281.25  1237.00  1291.50  1235.00         9.98      0.03
2  2018165  1239.70  1253.00  1253.00  1234.10         3.80     -0.02
3  2018164  1264.80  1256.86  1273.93  1256.86         2.88      0.01
4  2018163  1248.63  1255.82  1261.28  1240.64         3.92      0.00

In [9]:
x = df.iloc[:,[0,2,3,4,5]]
y = df.Close

In [10]:
x

        Date     Open     High      Low  Vol-Million
0    2018169  1281.80  1291.00  1264.05         2.86
1    2018166  1237.00  1291.50  1235.00         9.98
2    2018165  1253.00  1253.00  1234.10         3.80
3    2018164  1256.86  1273.93  1256.86         2.88
4    2018163  1255.82  1261.28  1240.64         3.92
..       ...      ...      ...      ...          ...
244  2017174   945.00   949.15   938.00         3.20
245  2017173   947.70   968.70   935.10         4.73
246  2017172   945.00   949.00   936.05         1.87
247  2017171   935.00   946.90   934.05         2.59
248  2017170   939.95   940.25   928.00         3.43

[249 rows x 5 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=1,shuffle=True)

In [12]:
x_train.shape

(199, 5)

In [13]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [14]:
dtr.score(x_test,y_test) # This is the regression so MAE, RMSE

0.9893881915006063

In [15]:
dtr.score(x_train,y_train)

1.0

In [16]:
from sklearn.metrics import mean_squared_error
y_pred = dtr.predict(x_test)
mean_squared_error(y_test, y_pred)

142.84448199999994

In [17]:
y_pred

array([1183.8 ,  935.45,  987.7 ,  923.9 , 1152.7 ,  994.05, 1164.55,
        988.4 ,  896.  , 1250.17,  943.35,  884.05, 1035.6 ,  908.25,
       1013.1 , 1152.7 ,  909.55, 1143.45, 1180.75, 1163.4 ,  983.75,
       1189.95, 1180.8 ,  912.25, 1020.85, 1021.3 ,  957.05,  951.95,
       1180.8 ,  972.05,  968.25, 1128.05, 1176.45,  968.25,  941.  ,
        984.7 , 1185.8 , 1171.45, 1216.7 ,  935.45,  914.95, 1179.5 ,
       1151.35, 1152.7 , 1194.55, 1022.9 , 1182.55, 1228.3 , 1170.7 ,
       1264.8 ])

In [18]:
df.columns

Index(['Date', 'Close', 'Open', 'High', 'Low', 'Vol-Million', 'Change %'], dtype='object')

In [ ]:
from sklearn.tree import export_text
export_text(dtr, feature_names = ['Date','Open','High','Low','Vol-Million'])

'|--- Low <= 1044.15\n|   |--- Low <= 948.38\n|   |   |--- High <= 921.55\n|   |   |   |--- High <= 899.65\n|   |   |   |   |--- Low <= 876.23\n|   |   |   |   |   |--- Open <= 892.80\n|   |   |   |   |   |   |--- value: [878.70]\n|   |   |   |   |   |--- Open >  892.80\n|   |   |   |   |   |   |--- value: [875.40]\n|   |   |   |   |--- Low >  876.23\n|   |   |   |   |   |--- High <= 887.67\n|   |   |   |   |   |   |--- value: [883.75]\n|   |   |   |   |   |--- High >  887.67\n|   |   |   |   |   |   |--- Date <= 2017253.00\n|   |   |   |   |   |   |   |--- value: [884.30]\n|   |   |   |   |   |   |--- Date >  2017253.00\n|   |   |   |   |   |   |   |--- value: [884.05]\n|   |   |   |--- High >  899.65\n|   |   |   |   |--- High <= 909.95\n|   |   |   |   |   |--- Low <= 894.65\n|   |   |   |   |   |   |--- Vol-Million <= 19.70\n|   |   |   |   |   |   |   |--- Low <= 891.17\n|   |   |   |   |   |   |   |   |--- Low <= 889.55\n|   |   |   |   |   |   |   |   |   |--- value: [895.35]\n|   |   |   |   |   |   |   |   |--- Low >  889.55\n|   |   |   |   |   |   |   |   |   |--- value: [895.60]\n|   |   |   |   |   |   |   |--- Low >  891.17\n|   |   |   |   |   |   |   |   |--- Low <= 893.32\n|   |   |   |   |   |   |   |   |   |--- value: [895.75]\n|   |   |   |   |   |   |   |   |--- Low >  893.32\n|   |   |   |   |   |   |   |   |   |--- value: [896.00]\n|   |   |   |   |   |   |--- Vol-Million >  19.70\n|   |   |   |   |   |   |   |--- value: [892.80]\n|   |   |   |   |   |--- Low >  894.65\n|   |   |   |   |   |   |--- Vol-Million <= 3.65\n|   |   |   |   |   |   |   |--- Vol-Million <= 2.67\n|   |   |   |   |   |   |   |   |--- value: [899.60]\n|   |   |   |   |   |   |   |--- Vol-Million >  2.67\n|   |   |   |   |   |   |   |   |--- Vol-Million <= 2.92\n|   |   |   |   |   |   |   |   |   |--- value: [899.90]\n|   |   |   |   |   |   |   |   |--- Vol-Million >  2.92\n|   |   |   |   |   |   |   |   |   |--- value: [899.80]\n|   |   |   |   |   |   |--- Vol-Million >  3.65\n|   |   |   |   |   |   |   |--- High <= 904.98\n|   |   |   |   |   |   |   |   |--- value: [903.05]\n|   |   |   |   |   |   |   |--- High >  904.98\n|   |   |   |   |   |   |   |   |--- value: [901.90]\n|   |   |   |   |--- High >  909.95\n|   |   |   |   |   |--- Low <= 901.97\n|   |   |   |   |   |   |--- Vol-Million <= 5.91\n|   |   |   |   |   |   |   |--- High <= 916.55\n|   |   |   |   |   |   |   |   |--- value: [903.55]\n|   |   |   |   |   |   |   |--- High >  916.55\n|   |   |   |   |   |   |   |   |--- value: [900.20]\n|   |   |   |   |   |   |--- Vol-Million >  5.91\n|   |   |   |   |   |   |   |--- value: [908.25]\n|   |   |   |   |   |--- Low >  901.97\n|   |   |   |   |   |   |--- Open <= 912.50\n|   |   |   |   |   |   |   |--- Vol-Million <= 12.11\n|   |   |   |   |   |   |   |   |--- value: [912.25]\n|   |   |   |   |   |   |   |--- Vol-Million >  12.11\n|   |   |   |   |   |   |   |   |--- value: [912.15]\n|   |   |   |   |   |   |--- Open >  912.50\n|   |   |   |   |   |   |   |--- value: [909.55]\n|   |   |--- High >  921.55\n|   |   |   |--- Low <= 925.70\n|   |   |   |   |--- High <= 928.98\n|   |   |   |   |   |--- Date <= 2017243.50\n|   |   |   |   |   |   |--- value: [914.95]\n|   |   |   |   |   |--- Date >  2017243.50\n|   |   |   |   |   |   |--- Low <= 915.00\n|   |   |   |   |   |   |   |--- Low <= 906.98\n|   |   |   |   |   |   |   |   |--- value: [920.15]\n|   |   |   |   |   |   |   |--- Low >  906.98\n|   |   |   |   |   |   |   |   |--- value: [919.95]\n|   |   |   |   |   |   |--- Low >  915.00\n|   |   |   |   |   |   |   |--- value: [922.90]\n|   |   |   |   |--- High >  928.98\n|   |   |   |   |   |--- Low <= 921.30\n|   |   |   |   |   |   |--- Low <= 919.77\n|   |   |   |   |   |   |   |--- Low <= 915.48\n|   |   |   |   |   |   |   |   |--- Low <= 899.10\n|   |   |   |   |   |   |   |   |   |--- value: [923.25]\n|   |   |   |   |   |   |   |   |--- Low >  899.10\n|   |   |   |   |   |   |   |   |   |--- value: [923.90]\n|   |   |   |   |   |   |   |--- Low >  915.48\n|   |   |   |   |   |   |   |   |--- Low <= 918.25\n|   |   |   |   |   |   |   |   |   |--- value: [926.65]\n|   |   |   |   |   |   |   |   |--- Low >  918.25\n|   |   |   |   |   |   |   |   |   |--- value: [927.30]\n|   |   |   |   |   |   |--- Low >  919.77\n|   |   |   |   |   |   |   |--- Open <= 928.90\n|   |   |   |   |   |   |   |   |--- value: [921.85]\n|   |   |   |   |   |   |   |--- Open >  928.90\n|   |   |   |   |   |   |   |   |--- value: [924.70]\n|   |   |   |   |   |--- Low >  921.30\n|   |   |   |   |   |   |--- Open <= 924.08\n|   |   |   |   |   |   |   |--- value: [928.70]\n|   |   |   |   |   |   |--- Open >  924.08\n|   |   |   |   |   |   |   |--- Low <= 923.12\n|   |   |   |   |   |   |   |   |--- Vol-Million <= 5.44\n|   |   |   |   |   |   |   |   |   |--- value: [924.35]\n|   |   |   |   |   |   |   |   |--- Vol-Million >  5.44\n|   |   |   |   |   |   |   |   |   |--- value: [926.50]\n|   |   |   |   |   |   |   |--- Low >  923.12\n|   |   |   |   |   |   |   |   |--- Low <= 925.38\n|   |   |   |   |   |   |   |   |   |--- Vol-Million <= 5.76\n|   |   |   |   |   |   |   |   |   |   |--- Low <= 924.48\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [927.05]\n|   |   |   |   |   |   |   |   |   |   |--- Low >  924.48\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [926.95]\n|   |   |   |   |   |   |   |   |   |--- Vol-Million >  5.76\n|   |   |   |   |   |   |   |   |   |   |--- value: [926.65]\n|   |   |   |   |   |   |   |   |--- Low >  925.38\n|   |   |   |   |   |   |   |   |   |--- value: [927.45]\n|   |   |   |--- Low >  925.70\n|   |   |   |   |--- High <= 947.23\n|   |   |   |   |   |--- High <= 938.98\n|   |   |   |   |   |   |--- Date <= 2017232.50\n|   |   |   |   |   |   |   |--- value: [935.55]\n|   |   |   |   |   |   |--- Date >  2017232.50\n|   |   |   |   |   |   |   |--- Vol-Million <= 3.29\n|   |   |   |   |   |   |   |   |--- High <= 937.40\n|   |   |   |   |   |   |   |   |   |--- value: [930.50]\n|   |   |   |   |   |   |   |   |--- High >  937.40\n|   |   |   |   |   |   |   |   |   |--- value: [930.70]\n|   |   |   |   |   |   |   |--- Vol-Million >  3.29\n|   |   |   |   |   |   |   |   |--- value: [930.10]\n|   |   |   |   |   |--- High >  938.98\n|   |   |   |   |   |   |--- Date <= 2017286.00\n|   |   |   |   |   |   |   |--- Open <= 941.90\n|   |   |   |   |   |   |   |   |--- value: [935.45]\n|   |   |   |   |   |   |   |--- Open >  941.90\n|   |   |   |   |   |   |   |   |--- value: [935.40]\n|   |   |   |   |   |   |--- Date >  2017286.00\n|   |   |   |   |   |   |   |--- Open <= 932.98\n|   |   |   |   |   |   |   |   |--- value: [939.50]\n|   |   |   |   |   |   |   |--- Open >  932.98\n|   |   |   |   |   |   |   |   |--- value: [939.00]\n|   |   |   |   |--- High >  947.23\n|   |   |   |   |   |--- High <= 958.35\n|   |   |   |   |   |   |--- Date <= 2017310.50\n|   |   |   |   |   |   |   |--- High <= 954.83\n|   |   |   |   |   |   |   |   |--- Vol-Million <= 13.42\n|   |   |   |   |   |   |   |   |   |--- Date <= 2017238.50\n|   |   |   |   |   |   |   |   |   |   |--- High <= 949.08\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [943.35]\n|   |   |   |   |   |   |   |   |   |   |--- High >  949.08\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [943.25]\n|   |   |   |   |   |   |   |   |   |--- Date >  2017238.50\n|   |   |   |   |   |   |   |   |   |   |--- value: [944.10]\n|   |   |   |   |   |   |   |   |--- Vol-Million >  13.42\n|   |   |   |   |   |   |   |   |   |--- value: [941.00]\n|   |   |   |   |   |   |   |--- High >  954.83\n|   |   |   |   |   |   |   |   |--- Low <= 939.30\n|   |   |   |   |   |   |   |   |   |--- value: [951.90]\n|   |   |   |   |   |   |   |   |--- Low >  939.30\n|   |   |   |   |   |   |   |   |   |--- Date <= 2017243.50\n|   |   |   |   |   |   |   |   |   |   |--- value: [947.00]\n|   |   |   |   |   |   |   |   |   |--- Date >  2017243.50\n|   |   |   |   |   |   |   |   |   |   |--- value: [946.35]\n|   |   |   |   |   |   |--- Date >  2017310.50\n|   |   |   |   |   |   |   |--- Open <= 948.55\n|   |   |   |   |   |   |   |   |--- value: [951.80]\n|   |   |   |   |   |   |   |--- Open >  948.55\n|   |   |   |   |   |   |   |   |--- value: [949.10]\n|   |   |   |   |   |--- High >  958.35\n|   |   |   |   |   |   |--- Open <= 956.00\n|   |   |   |   |   |   |   |--- Date <= 2017251.00\n|   |   |   |   |   |   |   |   |--- value: [957.05]\n|   |   |   |   |   |   |   |--- Date >  2017251.00\n|   |   |   |   |   |   |   |   |--- Date <= 2017312.00\n|   |   |   |   |   |   |   |   |   |--- value: [955.50]\n|   |   |   |   |   |   |   |   |--- Date >  2017312.00\n|   |   |   |   |   |   |   |   |   |--- value: [954.50]\n|   |   |   |   |   |   |--- Open >  956.00\n|   |   |   |   |   |   |   |--- Low <= 946.45\n|   |   |   |   |   |   |   |   |--- value: [950.90]\n|   |   |   |   |   |   |   |--- Low >  946.45\n|   |   |   |   |   |   |   |   |--- value: [952.30]\n|   |--- Low >  948.38\n|   |   |--- High <= 1013.88\n|   |   |   |--- High <= 987.08\n|   |   |   |   |--- Low <= 958.65\n|   |   |   |   |   |--- Low <= 949.67\n|   |   |   |   |   |   |--- value: [951.95]\n|   |   |   |   |   |--- Low >  949.67\n|   |   |   |   |   |   |--- Low <= 956.05\n|   |   |   |   |   |   |   |--- High <= 967.30\n|   |   |   |   |   |   |   |   |--- value: [962.05]\n|   |   |   |   |   |   |   |--- High >  967.30\n|   |   |   |   |   |   |   |   |--- value: [963.85]\n|   |   |   |   |   |   |--- Low >  956.05\n|   |   |   |   |   |   |   |--- Low <= 957.15\n|   |   |   |   |   |   |   |   |--- value: [958.80]\n|   |   |   |   |   |   |   |--- Low >  957.15\n|   |   |   |   |   |   |   |   |--- value: [960.55]\n|   |   |   |   |--- Low >  958.65\n|   |   |   |   |   |--- Date <= 2017197.50\n|   |   |   |   |   |   |--- High <= 982.48\n|   |   |   |   |   |   |   |--- value: [972.35]\n|   |   |   |   |   |   |--- High >  982.48\n|   |   |   |   |   |   |   |--- value: [977.05]\n|   |   |   |   |   |--- Date >  2017197.50\n|   |   |   |   |   |   |--- Date <= 2017323.00\n|   |   |   |   |   |   |   |--- Open <= 984.50\n|   |   |   |   |   |   |   |   |--- High <= 981.80\n|   |   |   |   |   |   |   |   |   |--- Open <= 973.48\n|   |   |   |   |   |   |   |   |   |   |--- value: [969.35]\n|   |   |   |   |   |   |   |   |   |--- Open >  973.48\n|   |   |   |   |   |   |   |   |   |   |--- value: [969.45]\n|   |   |   |   |   |   |   |   |--- High >  981.80\n|   |   |   |   |   |   |   |   |   |--- value: [968.25]\n|   |   |   |   |   |   |   |--- Open >  984.50\n|   |   |   |   |   |   |   |   |--- value: [970.95]\n|   |   |   |   |   |   |--- Date >  2017323.00\n|   |   |   |   |   |   |   |--- High <= 971.27\n|   |   |   |   |   |   |   |   |--- value: [966.30]\n|   |   |   |   |   |   |   |--- High >  971.27\n|   |   |   |   |   |   |   |   |--- value: [966.25]\n|   |   |   |--- High >  987.08\n|   |   |   |   |--- Low <= 984.80\n|   |   |   |   |   |--- Open <= 978.00\n|   |   |   |   |   |   |--- High <= 1000.00\n|   |   |   |   |   |   |   |--- Low <= 971.80\n|   |   |   |   |   |   |   |   |--- Date <= 2017323.50\n|   |   |   |   |   |   |   |   |   |--- Open <= 963.90\n|   |   |   |   |   |   |   |   |   |   |--- value: [988.40]\n|   |   |   |   |   |   |   |   |   |--- Open >  963.90\n|   |   |   |   |   |   |   |   |   |   |--- value: [987.70]\n|   |   |   |   |   |   |   |   |--- Date >  2017323.50\n|   |   |   |   |   |   |   |   |   |--- value: [991.25]\n|   |   |   |   |   |   |   |--- Low >  971.80\n|   |   |   |   |   |   |   |   |--- value: [984.05]\n|   |   |   |   |   |   |--- High >  1000.00\n|   |   |   |   |   |   |   |--- value: [997.35]\n|   |   |   |   |   |--- Open >  978.00\n|   |   |   |   |   |   |--- Low <= 968.45\n|   |   |   |   |   |   |   |--- High <= 998.15\n|   |   |   |   |   |   |   |   |--- value: [976.10]\n|   |   |   |   |   |   |   |--- High >  998.15\n|   |   |   |   |   |   |   |   |--- value: [972.05]\n|   |   |   |   |   |   |--- Low >  968.45\n|   |   |   |   |   |   |   |--- Low <= 982.65\n|   |   |   |   |   |   |   |   |--- High <= 994.38\n|   |   |   |   |   |   |   |   |   |--- High <= 988.83\n|   |   |   |   |   |   |   |   |   |   |--- value: [979.85]\n|   |   |   |   |   |   |   |   |   |--- High >  988.83\n|   |   |   |   |   |   |   |   |   |   |--- Vol-Million <= 1.91\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [981.45]\n|   |   |   |   |   |   |   |   |   |   |--- Vol-Million >  1.91\n|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n|   |   |   |   |   |   |   |   |--- High >  994.38\n|   |   |   |   |   |   |   |   |   |--- Low <= 973.77\n|   |   |   |   |   |   |   |   |   |   |--- value: [985.35]\n|   |   |   |   |   |   |   |   |   |--- Low >  973.77\n|   |   |   |   |   |   |   |   |   |   |--- Low <= 980.77\n|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n|   |   |   |   |   |   |   |   |   |   |--- Low >  980.77\n|   |   |   |   |   |   |   |   |   |   |   |--- value: [984.70]\n|   |   |   |   |   |   |   |--- Low >  982.65\n|   |   |   |   |   |   |   |   |--- value: [990.30]\n|   |   |   |   |--- Low >  984.80\n|   |   |   |   |   |--- Date <= 2017272.50\n|   |   |   |   |   |   |--- High <= 1005.88\n|   |   |   |   |   |   |   |--- value: [994.05]\n|   |   |   |   |   |   |--- High >  1005.88\n|   |   |   |   |   |   |   |--- value: [993.35]\n|   |   |   |   |   |--- Date >  2017272.50\n|   |   |   |   |   |   |--- Date <= 2017343.50\n|   |   |   |   |   |   |   |--- Date <= 2017341.50\n|   |   |   |   |   |   |   |   |--- Open <= 997.85\n|   |   |   |   |   |   |   |   |   |--- value: [999.80]\n|   |   |   |   |   |   |   |   |--- Open >  997.85\n|   |   |   |   |   |   |   |   |   |--- value: [998.75]\n|   |   |   |   |   |   |   |--- Date >  2017341.50\n|   |   |   |   |   |   |   |   |--- value: [1001.85]\n|   |   |   |   |   |   |--- Date >  2017343.50\n|   |   |   |   |   |   |   |--- value: [1005.30]\n|   |   |--- High >  1013.88\n|   |   |   |--- Low <= 1019.32\n|   |   |   |   |--- High <= 1024.05\n|   |   |   |   |   |--- Date <= 2017353.50\n|   |   |   |   |   |   |--- Open <= 1008.08\n|   |   |   |   |   |   |   |--- High <= 1017.15\n|   |   |   |   |   |   |   |   |--- value: [1013.10]\n|   |   |   |   |   |   |   |--- High >  1017.15\n|   |   |   |   |   |   |   |   |--- Date <= 2017270.00\n|   |   |   |   |   |   |   |   |   |--- value: [1011.20]\n|   |   |   |   |   |   |   |   |--- Date >  2017270.00\n|   |   |   |   |   |   |   |   |   |--- value: [1009.55]\n|   |   |   |   |   |   |--- Open >  1008.08\n|   |   |   |   |   |   |   |--- Vol-Million <= 3.70\n|   |   |   |   |   |   |   |   |--- Date <= 2017350.00\n|   |   |   |   |   |   |   |   |   |--- value: [1003.75]\n|   |   |   |   |   |   |   |   |--- Date >  2017350.00\n|   |   |   |   |   |   |   |   |   |--- value: [1003.95]\n|   |   |   |   |   |   |   |--- Vol-Million >  3.70\n|   |   |   |   |   |   |   |   |--- value: [1005.55]\n|   |   |   |   |   |--- Date >  2017353.50\n|   |   |   |   |   |   |--- Open <= 1013.05\n|   |   |   |   |   |   |   |--- value: [1015.85]\n|   |   |   |   |   |   |--- Open >  1013.05\n|   |   |   |   |   |   |   |--- value: [1015.40]\n|   |   |   |   |--- High >  1024.05\n|   |   |   |   |   |--- Vol-Million <= 2.72\n|   |   |   |   |   |   |--- value: [1016.60]\n|   |   |   |   |   |--- Vol-Million >  2.72\n|   |   |   |   |   |   |--- High <= 1027.83\n|   |   |   |   |   |   |   |--- value: [1022.90]\n|   |   |   |   |   |   |--- High >  1027.83\n|   |   |   |   |   |   |   |--- Low <= 1008.32\n|   |   |   |   |   |   |   |   |--- value: [1020.85]\n|   |   |   |   |   |   |   |--- Low >  1008.32\n|   |   |   |   |   |   |   |   |--- value: [1021.30]\n|   |   |   |--- Low >  1019.32\n|   |   |   |   |--- High <= 1044.70\n|   |   |   |   |   |--- High <= 1041.75\n|   |   |   |   |   |   |--- Low <= 1025.20\n|   |   |   |   |   |   |   |--- Low <= 1021.52\n|   |   |   |   |   |   |   |   |--- value: [1036.05]\n|   |   |   |   |   |   |   |--- Low >  1021.52\n|   |   |   |   |   |   |   |   |--- value: [1035.60]\n|   |   |   |   |   |   |--- Low >  1025.20\n|   |   |   |   |   |   |   |--- value: [1034.25]\n|   |   |   |   |   |--- High >  1041.75\n|   |   |   |   |   |   |--- High <= 1043.25\n|   |   |   |   |   |   |   |--- value: [1029.70]\n|   |   |   |   |   |   |--- High >  1043.25\n|   |   |   |   |   |   |   |--- value: [1033.55]\n|   |   |   |   |--- High >  1044.70\n|   |   |   |   |   |--- Date <= 2018009.50\n|   |   |   |   |   |   |--- Low <= 1029.45\n|   |   |   |   |   |   |   |--- value: [1041.35]\n|   |   |   |   |   |   |--- Low >  1029.45\n|   |   |   |   |   |   |   |--- value: [1042.05]\n|   |   |   |   |   |--- Date >  2018009.50\n|   |   |   |   |   |   |--- value: [1052.25]\n|--- Low >  1044.15\n|   |--- High <= 1179.55\n|   |   |--- High <= 1135.40\n|   |   |   |--- High <= 1105.12\n|   |   |   |   |--- Date <= 2018013.50\n|   |   |   |   |   |--- Low <= 1062.90\n|   |   |   |   |   |   |--- value: [1075.80]\n|   |   |   |   |   |--- Low >  1062.90\n|   |   |   |   |   |   |--- value: [1078.45]\n|   |   |   |   |--- Date >  2018013.50\n|   |   |   |   |   |--- value: [1081.15]\n|   |   |   |--- High >  1105.12\n|   |   |   |   |--- Date <= 2018100.50\n|   |   |   |   |   |--- High <= 1129.02\n|   |   |   |   |   |   |--- Low <= 1100.68\n|   |   |   |   |   |   |   |--- Date <= 2018044.00\n|   |   |   |   |   |   |   |   |--- Open <= 1107.38\n|   |   |   |   |   |   |   |   |   |--- value: [1107.75]\n|   |   |   |   |   |   |   |   |--- Open >  1107.38\n|   |   |   |   |   |   |   |   |   |--- value: [1102.80]\n|   |   |   |   |   |   |   |--- Date >  2018044.00\n|   |   |   |   |   |   |   |   |--- value: [1097.75]\n|   |   |   |   |   |   |--- Low >  1100.68\n|   |   |   |   |   |   |   |--- Date <= 2018069.50\n|   |   |   |   |   |   |   |   |--- Date <= 2018039.00\n|   |   |   |   |   |   |   |   |   |--- value: [1109.05]\n|   |   |   |   |   |   |   |   |--- Date >  2018039.00\n|   |   |   |   |   |   |   |   |   |--- value: [1109.15]\n|   |   |   |   |   |   |   |--- Date >  2018069.50\n|   |   |   |   |   |   |   |   |--- Low <= 1105.98\n|   |   |   |   |   |   |   |   |   |--- value: [1113.40]\n|   |   |   |   |   |   |   |   |--- Low >  1105.98\n|   |   |   |   |   |   |   |   |   |--- value: [1111.25]\n|   |   |   |   |   |--- High >  1129.02\n|   |   |   |   |   |   |--- Low <= 1092.12\n|   |   |   |   |   |   |   |--- value: [1122.85]\n|   |   |   |   |   |   |--- Low >  1092.12\n|   |   |   |   |   |   |   |--- value: [1114.45]\n|   |   |   |   |--- Date >  2018100.50\n|   |   |   |   |   |--- Low <= 1115.75\n|   |   |   |   |   |   |--- Low <= 1114.42\n|   |   |   |   |   |   |   |--- value: [1125.95]\n|   |   |   |   |   |   |--- Low >  1114.42\n|   |   |   |   |   |   |   |--- value: [1125.20]\n|   |   |   |   |   |--- Low >  1115.75\n|   |   |   |   |   |   |--- value: [1124.25]\n|   |   |--- High >  1135.40\n|   |   |   |--- High <= 1160.65\n|   |   |   |   |--- High <= 1151.33\n|   |   |   |   |   |--- Low <= 1127.17\n|   |   |   |   |   |   |--- Vol-Million <= 3.10\n|   |   |   |   |   |   |   |--- Vol-Million <= 2.69\n|   |   |   |   |   |   |   |   |--- value: [1124.20]\n|   |   |   |   |   |   |   |--- Vol-Million >  2.69\n|   |   |   |   |   |   |   |   |--- value: [1127.00]\n|   |   |   |   |   |   |--- Vol-Million >  3.10\n|   |   |   |   |   |   |   |--- Vol-Million <= 4.67\n|   |   |   |   |   |   |   |   |--- High <= 1147.95\n|   |   |   |   |   |   |   |   |   |--- Open <= 1123.40\n|   |   |   |   |   |   |   |   |   |   |--- value: [1134.25]\n|   |   |   |   |   |   |   |   |   |--- Open >  1123.40\n|   |   |   |   |   |   |   |   |   |   |--- Low <= 1121.70\n|   |   |   |   |   |   |   |   |   |   |   |--- va