In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [3]:
df.shape

(891, 12)

In [4]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# df.drop(df['Cabin'],axis=1, inplace=True)
del df['Cabin']
df.head()

   PassengerId  Survived  Pclass  ...            Ticket     Fare  Embarked
0            1         0       3  ...         A/5 21171   7.2500         S
1            2         1       1  ...          PC 17599  71.2833         C
2            3         1       3  ...  STON/O2. 3101282   7.9250         S
3            4         1       1  ...            113803  53.1000         S
4            5         0       3  ...            373450   8.0500         S

[5 rows x 11 columns]

In [6]:
x = ['Sex','Embarked']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in x:
    df[i] = le.fit_transform(df[i])

In [7]:
df.head()

   PassengerId  Survived  Pclass  ...            Ticket     Fare  Embarked
0            1         0       3  ...         A/5 21171   7.2500         2
1            2         1       1  ...          PC 17599  71.2833         0
2            3         1       3  ...  STON/O2. 3101282   7.9250         2
3            4         1       1  ...            113803  53.1000         2
4            5         0       3  ...            373450   8.0500         2

[5 rows x 11 columns]

In [8]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [9]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.head()

/var/folders/fh/knfvlly12f53mfr4d69dnwhw0000gn/T/ipykernel_16323/3419160234.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

   PassengerId  Survived  Pclass  ...            Ticket     Fare  Embarked
0            1         0       3  ...         A/5 21171   7.2500         2
1            2         1       1  ...          PC 17599  71.2833         0
2            3         1       3  ...  STON/O2. 3101282   7.9250         2
3            4         1       1  ...            113803  53.1000         2
4            5         0       3  ...            373450   8.0500         2

[5 rows x 11 columns]

In [10]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [11]:
df.head()

   PassengerId  Survived  Pclass  ...            Ticket     Fare  Embarked
0            1         0       3  ...         A/5 21171   7.2500         2
1            2         1       1  ...          PC 17599  71.2833         0
2            3         1       3  ...  STON/O2. 3101282   7.9250         2
3            4         1       1  ...            113803  53.1000         2
4            5         0       3  ...            373450   8.0500         2

[5 rows x 11 columns]

In [12]:
df.corr(numeric_only=True)

             PassengerId  Survived    Pclass  ...     Parch      Fare  Embarked
PassengerId     1.000000 -0.005007 -0.035144  ... -0.001652  0.012658  0.013083
Survived       -0.005007  1.000000 -0.338481  ...  0.081629  0.257307 -0.163517
Pclass         -0.035144 -0.338481  1.000000  ...  0.018443 -0.549500  0.157112
Sex             0.042939 -0.543351  0.131900  ... -0.245489 -0.182333  0.104057
Age             0.033207 -0.069809 -0.331339  ... -0.179191  0.091566 -0.022239
SibSp          -0.057527 -0.035322  0.083081  ...  0.414838  0.159651  0.066654
Parch          -0.001652  0.081629  0.018443  ...  1.000000  0.216225  0.038322
Fare            0.012658  0.257307 -0.549500  ...  0.216225  1.000000 -0.221226
Embarked        0.013083 -0.163517  0.157112  ...  0.038322 -0.221226  1.000000

[9 rows x 9 columns]

In [13]:
x = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
y = df.Survived
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,shuffle=True)

In [14]:
# Building model Decision tree classifier -> because its a binary classification
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
dtc.score(x_test,y_test)

0.776536312849162

In [16]:
dtc.score(x_train,y_train)

0.9803370786516854

In [17]:
y_pred = dtc.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[83, 22],
       [18, 56]])

In [19]:
# Implementing the logictic regression -> Model number 2
from sklearn.linear_model import LogisticRegression
lor = LogisticRegression()
lor.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
lor.score(x_test,y_test)

0.8100558659217877

In [21]:
lor.score(x_train,y_train)

0.8019662921348315

In [22]:
# Implementing the Random forest classifier for removing the overfitting problem in the Decision tree classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100,max_depth=5,random_state=42) # What is this ?
rfc.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [23]:
rfc.score(x_test,y_test)

0.8044692737430168

In [24]:
rfc.score(x_train,y_train)

0.8567415730337079

# GridSearch

In [29]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
svm = SVC()
gv = {
    "kernel":["rbf","sigmoid"],
    "C": [1000,100,10,1],
    "gamma": ["auto","scale"]
}
gs = GridSearchCV(estimator = svm,
                  param_grid=gv,
                  scoring="accuracy",
                  cv=5, verbose=1)

gs.fit(x_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1000, 100, 10, 1], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid']},
             scoring='accuracy', verbose=1)

In [30]:

gs.best_estimator_

SVC(C=1000)

In [31]:
gs.score(x_train,y_train)

0.8328651685393258

In [32]:
gs.score(x_test,y_test)

0.8044692737430168